### ISSUE TITLE
typo in PolicyInput for "odrl:prohibition" and "odrl:obligation" fields

### ISSUE THREAD

**Issue by janpmeyer** [Think-iT-Labs/edc-connector-client#100]
### Check for existing issues

- [X] Completed

### Describe the bug

The fields in the PolicyInput entity need to be in singular:

  prohibitions -> prohibition
  obligations -> obligation

If they are spelled in plural the mapping is not working correctly and it seems like
that the information does not get into the EDC-Connector

### Provide steps to reproduce it

Try to add an policyDefinition with a policy including a prohibitbition and a obligation.

It should be seen, that this information gets lost in Version beta5

**Comment by ndr-brt** [comment]
on the same side, we should add the methods on the `Policy` object for prohibitions and obligations as it was done for permissions
