### ISSUE TITLE
feat: add federated catalog Request to the catalog manager

### ISSUE THREAD

**Issue by janpmeyer** [Think-iT-Labs/edc-connector-client#102]
### Check for existing issues

- [X] Completed

### Describe the feature

With the edc-connector-client you should also be able to request the federated catalog,
and not only the catalog of a specific connector.

**Comment by janpmeyer** [comment]
@ndr-brt

Is this still an interesting feature for you guys, or will this issue not be followed in the Future?

**Comment by ndr-brt** [comment]
definitely yes, there's a good chance that the FederatedCatalog will change and for the moment there's no interest in implementing the current api, but we're open to contributions
