### ISSUE TITLE
Get asset data address

### ISSUE THREAD

**Issue by OlfaBensoussia** [Think-iT-Labs/edc-connector-client#22]
### Check for existing issues

- [X] Completed

### Describe the feature

We want to add an endpoint that takes an `assetId` and returns its related data address

### TODOs
- [x] NodeJS implementation
- [x] Go implementation
- [ ] Rust implementation

**Comment by fdionisi** [comment]
@OlfaBensoussia, this would be awesome! Is there already an endpoint for it, or is something will come up next in the Connector?

**Comment by ndr-brt** [comment]
Not needed anymore because on `/v3/assets` endpoint the `DataAddress` is part of the `Asset`
